server:
  port: 8080
  servlet:
    encoding:
      force: true
      charset: UTF-8
spring:
  freemarker:
        allow-request-override: false
        cache: false
        check-template-location: true
        content-type: text/html; charset=utf-8
        expose-request-attributes: false
        expose-session-attributes: false
        expose-spring-macro-helpers: false
        suffix: .ftlh
        template-loader-path: classpath:/templates
  ###指定log4j.properties配置文件路径
#logging:
#  config: classpath:log4j.properties
#  level:
#    org.springframework: INFO
#    org.springframework.boot: INFO

